### ISSUE TITLE
Error when using model created with option use_identity_learning=true

### ISSUE THREAD

**Issue by VirtualAI** [simontomaskarlsson/CycleGAN-Keras#14]
All is working and settings not changed. If i then switch use_identity_learning to true, model is still created successfull, but if i want to create images with it following error appears:
Do you have any ideas? Thanks. :)

Are you sure you want to generate synthetic images instead of training? (y/n): y
Traceback (most recent call last):
  File "C:\Users\micha\Desktop\CycleGAN-Keras-master\model.py", line 938, in <module>
    GAN = CycleGAN()
  File "C:\Users\micha\Desktop\CycleGAN-Keras-master\model.py", line 254, in __init__
    self.load_model_and_generate_synthetic_images()
  File "C:\Users\micha\Desktop\CycleGAN-Keras-master\model.py", line 845, in load_model_and_generate_synthetic_images
    self.load_model_and_weights(self.G_A2B)
  File "C:\Users\micha\Desktop\CycleGAN-Keras-master\model.py", line 839, in load_model_and_weights
    model.load_weights(path_to_weights)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\saving.py", line 1030, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 47 layers into a model with 51 layers.

**Comment by simontomaskarlsson** [comment]
Right, that is an error I have forgotten to fix. Easy to handle though since the identity training does not change the model, it just alters the training process. So when you have trained a model with identity learning you don't need to have it set when you want to use it to generate images.

You can just switch it off and generate you images and you will have the intended results.

**Comment by VirtualAI** [comment]
Thank you very much :), problem solved
